#!/usr/bin/env bash
# Setup the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -n "$DEVCONTAINER" ];then
  python3 -m venv venv
  source venv/bin/activate
fi

pip install pre-commit
pre-commit install

python3 -m pip install -e .
