#!/usr/bin/env bash
# Setup the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

curl -LsSf https://astral.sh/uv/install.sh | sh
uv venv venv
. venv/bin/activate
uv pip install -U pip setuptools pre-commit
uv pip install -r requirements_test.txt
uv pip install -e .[server]

pre-commit install
