name: CI

on:
  push:
    branches:
      - dev
  pull_request: ~

jobs:
  shared-ci:
    uses: zigpy/workflows/.github/workflows/ci.yml@main
    with:
      CODE_FOLDER: zhaws
      CACHE_VERSION: 2
      PYTHON_VERSION_DEFAULT: 3.12
      PRE_COMMIT_CACHE_PATH: ~/.cache/pre-commit
      MINIMUM_COVERAGE_PERCENTAGE: 95
      PYTHON_MATRIX: "3.12"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}